### ISSUE TITLE
chinese-hints.js在Vimperator 3.14.0中无法使用

### ISSUE THREAD

**Issue by longdanie** [grassofhust/dotfiles#3]
Firefox 的版本是 49.0.1，Vimperator 的版本是3.14.0，按照说明安装好插件，无法启用拼音搜索，作者能更新一下吗？

**Comment by grassofhust** [comment]
```
set hintmatching=custom
```

设置这个选项就可以，这个不是用于搜索的。通过按 ``f`` 键快速定位页面链接。

我本机是可以用的。

**Comment by longdanie** [comment]
不好意思，可以使用了，我把家目录搞错了，才导致插件不能起作用。
